version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  groups:
    inmanta-dev-dependencies:
      patterns:
        - "inmanta-dev-dependencies"
        - "pytest"
