version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "ncdiff"
    update-types: ["version-update:semver-major"]
    # Same version as the yang module
